import { accountsModule } from "./accounts/api";
import { cpmModule } from "./cpm/api";
import { crmModule } from "./crm/api";
import { dmModule } from "./dm/api";
import { fmModule } from "./fm/api";
import { useCompanyModule } from "./hooks/useModule";
import { hrmModule } from "./hrm/api";
import { logsModule } from "./logs/api";
import { manageModule } from "./manage/api";
import { pricingModule } from "./pricing/api";
import { storageModule } from "./storage/api";
import { storageDbModule } from "./storage/db/api";
import { storageMediaModule } from "./storage/media/api";
import { supportModule } from "./support/api";
import { wmModule } from "./wm/api";

export const useStorage = () => useCompanyModule(storageModule);
export const useStorageDb = () => useCompanyModule(storageDbModule);
export const useStorageMedia = () => useCompanyModule(storageMediaModule);
export const useAccounts = () => useCompanyModule(accountsModule);
export const useHrm = () => useCompanyModule(hrmModule);
export const useFm = () => useCompanyModule(fmModule);
export const useLogs = () => useCompanyModule(logsModule);
export const useCrm = () => useCompanyModule(crmModule);
export const useWm = () => useCompanyModule(wmModule);
export const useDm = () => useCompanyModule(dmModule);
export const useCpm = () => useCompanyModule(cpmModule);
export const usePricing = () => useCompanyModule(pricingModule);
export const useSupport = () => useCompanyModule(supportModule);
export const useManage = () => useCompanyModule(manageModule);